#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

# ── Colour helpers ───────────────────────────────────────────────────────────── #
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; RESET='\033[0m'

info()    { echo -e "${CYAN}[INFO]${RESET}  $*"; }
success() { echo -e "${GREEN}[OK]${RESET}    $*"; }
warn()    { echo -e "${YELLOW}[WARN]${RESET}  $*"; }
error()   { echo -e "${RED}[ERROR]${RESET} $*" >&2; exit 1; }
header()  { echo -e "\n${BOLD}${CYAN}══════════════════════════════════════════${RESET}"; \
            echo -e "${BOLD}${CYAN}  $*${RESET}"; \
            echo -e "${BOLD}${CYAN}══════════════════════════════════════════${RESET}"; }

# ── Root check ───────────────────────────────────────────────────────────────── #
[[ $EUID -eq 0 ]] || error "This script must be run as root (sudo bash $0)"

# ============================================================================== #
#  SECTION 0 — Collect user-defined variables
# ============================================================================== #
header "STEP 0 · Configuration Input"

echo ""
echo -e "${BOLD}Please provide the following values.${RESET}"
echo -e "Press ENTER to accept the default shown in [brackets].\n"

read -rp "  Your Employee ID              : " Employee_ID
[[ -z "$Employee_ID" ]] && error "Employee ID cannot be empty."

read -rp "  Your Full Name               : " Employee_NAME
[[ -z "$Employee_NAME" ]] && error "Employee Name cannot be empty."

read -rp "  SSH port to use        [2222]: " SSH_PORT
SSH_PORT="${SSH_PORT:-2222}"
[[ "$SSH_PORT" =~ ^[0-9]+$ ]] || error "Port must be a number."

read -rp "  Cowrie honeypot port   [2223]: " COWRIE_PORT
COWRIE_PORT="${COWRIE_PORT:-2223}"
[[ "$COWRIE_PORT" =~ ^[0-9]+$ ]] || error "Port must be a number."

read -rsp "  Cowrie 'staff' password      : " STAFF_PASS; echo
[[ -z "$STAFF_PASS" ]] && error "Staff password cannot be empty."

# Detect the primary non-loopback network interface
DEFAULT_IFACE=$(ip -br link | awk '$2=="UP" && $1!="lo" {print $1; exit}')
read -rp "  Network interface   [${DEFAULT_IFACE}]: " NET_IFACE
NET_IFACE="${NET_IFACE:-$DEFAULT_IFACE}"

echo ""
echo -e "${BOLD}──── Summary of inputs ────${RESET}"
echo "  Employee ID    : $Employee_ID"
echo "  Employee Name  : $Employee_NAME"
echo "  SSH Port      : $SSH_PORT"
echo "  Cowrie Port   : $COWRIE_PORT"
echo "  Staff Pass    : (hidden)"
echo "  Interface     : $NET_IFACE"
echo ""
read -rp "Proceed with these values? [y/N]: " CONFIRM
[[ "${CONFIRM,,}" == "y" ]] || { echo "Aborted."; exit 0; }

# ============================================================================== #
#  SECTION 1 — OpenSSH Server
# ============================================================================== #
header "STEP 1 · OpenSSH Server — Install & Harden"

# 1.1 Install
info "Installing openssh-server …"
dnf install -y openssh-server &>/dev/null
systemctl enable --now sshd
success "openssh-server installed and started."

# 1.2 Backup original config
SSHD_CONF="/etc/ssh/sshd_config"
cp -n "${SSHD_CONF}" "${SSHD_CONF}.bak.$(date +%F)"
success "Original sshd_config backed up."

# 1.3 Write hardened sshd_config
info "Writing hardened sshd_config …"
cat > "${SSHD_CONF}" <<SSHD_EOF
# /etc/ssh/sshd_config
# Generated by rhel10_security_setup.sh — $(date)

# ── Port ────────────────────────────────────────────────────────────────────── #
Port ${SSH_PORT}
AddressFamily                   any
ListenAddress                   0.0.0.0:$SSH_PORT

# ── Authentication ──────────────────────────────────────────────────────────── #
PasswordAuthentication no
PubkeyAuthentication yes
AuthorizedKeysFile .ssh/authorized_keys
PermitRootLogin no
HostbasedAuthentication no
PermitEmptyPasswords no

# ── MFA (keyboard-interactive for TOTP) ─────────────────────────────────────── #
KbdInteractiveAuthentication yes
AuthenticationMethods publickey,keyboard-interactive

# ── Forwarding / Tunnelling ─────────────────────────────────────────────────── #
AllowTCPForwarding no
GatewayPorts no
X11Forwarding no

# ── Login Banner ────────────────────────────────────────────────────────────── #
Banner /etc/ssh/banner.txt

# ── Misc Hardening ──────────────────────────────────────────────────────────── #
UseDNS no
MaxAuthTries 3
LoginGraceTime 30
Protocol 2
SSHD_EOF
success "sshd_config written."

# 1.4 Login banner
info "Creating login banner …"
cat > /etc/ssh/banner.txt <<BANNER_EOF
*************************************************************
*  AUTHORISED ACCESS ONLY                                   *
*  ID   : ${Employee_ID}
*  Name : ${Employee_NAME}
*  Unauthorised access is strictly prohibited and may be    *
*  subject to criminal prosecution.                         *
*************************************************************
BANNER_EOF
success "Login banner written to /etc/ssh/banner.txt"

# 1.5 SELinux — label the new SSH port
info "Labelling port ${SSH_PORT} in SELinux …"
if command -v semanage &>/dev/null; then
    # Only add if not already present
    semanage port -l | grep -q "${SSH_PORT}.*ssh_port_t" || \
        semanage port -a -t ssh_port_t -p tcp "${SSH_PORT}"
    success "SELinux port label set."
else
    warn "semanage not found — install policycoreutils-python-utils manually."
fi

# 1.6 Syntax-check and restart
info "Validating sshd configuration …"
sshd -t || error "sshd_config has syntax errors — check ${SSHD_CONF}"
systemctl restart sshd
success "sshd restarted on port ${SSH_PORT}."

# ============================================================================== #
#  SECTION 2 — MFA (Google Authenticator PAM / TOTP)
# ============================================================================== #
header "STEP 2 · Multi-Factor Authentication (TOTP)"

# 2.1 Enable EPEL and install google-authenticator
info "Enabling EPEL and installing google-authenticator …"
dnf install -y epel-release &>/dev/null
dnf install -y google-authenticator qrencode &>/dev/null
success "google-authenticator installed."

# 2.2 Configure PAM for sshd
PAM_SSHD="/etc/pam.d/sshd"
info "Configuring PAM for sshd …"

# Backup
cp -n "${PAM_SSHD}" "${PAM_SSHD}.bak.$(date +%F)"

# Prepend the google-authenticator line if not already present
if ! grep -q "pam_google_authenticator" "${PAM_SSHD}"; then
    sed -i '1s/^/auth required pam_google_authenticator.so nullok\n/' "${PAM_SSHD}"
fi

# Comment out password-auth substack to prevent password fallback
sed -i 's/^auth.*substack.*password-auth/# &/' "${PAM_SSHD}"

success "PAM configured. Users must run 'google-authenticator' once to enrol TOTP."

# 2.3 Restart sshd to pick up PAM changes
systemctl restart sshd
success "sshd restarted with MFA support."

echo ""
warn "ACTION REQUIRED (per SSH user, run as that user):"
echo "    google-authenticator"
echo "  Then scan the QR code with Google Authenticator or Authy."

# ============================================================================== #
#  SECTION 3 — Cowrie Honeypot
# ============================================================================== #
header "STEP 3 · Cowrie Honeypot"

# 3.1 Install dependencies
info "Installing Cowrie build dependencies …"
dnf install -y python3 python3-pip python3-virtualenv git \
               libffi-devel openssl-devel gcc make &>/dev/null
success "Dependencies installed."

# 3.2 Create cowrie system user (idempotent)
if ! id cowrie &>/dev/null; then
    useradd -r -d /opt/cowrie -m -s /sbin/nologin cowrie
    success "System user 'cowrie' created."
else
    info "System user 'cowrie' already exists — skipping."
fi

# 3.3 Clone and install Cowrie
if [[ ! -d /opt/cowrie/.git ]]; then
    info "Cloning Cowrie from GitHub …"
    sudo -u cowrie git clone https://github.com/cowrie/cowrie /opt/cowrie
    success "Cowrie cloned."
else
    info "Cowrie already cloned — pulling latest …"
    sudo -u cowrie git -C /opt/cowrie pull --ff-only
fi

info "Setting up Python virtualenv and installing Cowrie requirements …"
sudo -u cowrie bash -c '
    cd /opt/cowrie
    python3 -m virtualenv cowrie-env
    source cowrie-env/bin/activate
    pip install --upgrade pip --quiet
    pip install -r requirements.txt --quiet
'
success "Cowrie Python environment ready."

# 3.4 Write cowrie.cfg
COWRIE_CFG="/opt/cowrie/etc/cowrie.cfg"
if [[ ! -f "${COWRIE_CFG}" ]]; then
    sudo -u cowrie cp /opt/cowrie/etc/cowrie.cfg.dist "${COWRIE_CFG}"
fi

info "Writing Cowrie configuration …"

# Use a Python-style sed to update / add keys in the [honeypot] section
python3 - <<PYEOF
import re, pathlib

cfg_path = pathlib.Path("${COWRIE_CFG}")
text = cfg_path.read_text()

replacements = {
    "hostname":           "${Employee_ID}",
    "listen_endpoints":   "tcp:${COWRIE_PORT}:interface=0.0.0.0",
    "log_path":           "var/log/cowrie",
    "download_path":      "var/lib/cowrie/downloads",
    "share_path":         "share/cowrie",
    "state_path":         "var/lib/cowrie",
}

for key, val in replacements.items():
    pattern = rf"(?m)^(#?\s*{re.escape(key)}\s*=).*$"
    replacement = f"{key} = {val}"
    if re.search(pattern, text):
        text = re.sub(pattern, replacement, text)
    else:
        # append after [honeypot] header if key is missing
        text = text.replace("[honeypot]", f"[honeypot]\n{replacement}", 1)

cfg_path.write_text(text)
print("cowrie.cfg updated.")
PYEOF

chown cowrie:cowrie "${COWRIE_CFG}"
success "cowrie.cfg configured (hostname=${Employee_ID}, port=${COWRIE_PORT})."

# 3.5 Write userdb.txt
info "Writing Cowrie userdb.txt …"
mkdir -p /opt/cowrie/etc
cat > /opt/cowrie/etc/userdb.txt <<USERDB_EOF
# Cowrie user database — generated by rhel10_security_setup.sh
# Format: username:uid:password
#   !password  = always reject (trap / log all attempts)
#   *          = accept any password

# root — deny every password (honeypot trap)
root:0:!

# staff — accept only the defined password
staff:1000:${STAFF_PASS}
USERDB_EOF

chown cowrie:cowrie /opt/cowrie/etc/userdb.txt
success "userdb.txt written (root=trap, staff=password-protected)."

# 3.6 Create required runtime directories
sudo -u cowrie mkdir -p \
    /opt/cowrie/var/log/cowrie \
    /opt/cowrie/var/lib/cowrie/downloads \
    /opt/cowrie/var/run

# 3.7 systemd service for Cowrie
info "Creating systemd service for Cowrie …"
cat > /etc/systemd/system/cowrie.service <<'SVC_EOF'
[Unit]
Description=Cowrie SSH Honeypot
After=network.target

[Service]
Type=forking
User=cowrie
Group=cowrie
WorkingDirectory=/opt/cowrie
ExecStart=/opt/cowrie/bin/cowrie start
ExecStop=/opt/cowrie/bin/cowrie stop
PIDFile=/opt/cowrie/var/run/cowrie.pid
Restart=on-failure
RestartSec=5s

[Install]
WantedBy=multi-user.target
SVC_EOF

systemctl daemon-reload
systemctl enable cowrie
systemctl start cowrie || warn "Cowrie failed to start — check: journalctl -u cowrie"
success "Cowrie service enabled and started on port ${COWRIE_PORT}."

# ============================================================================== #
#  SECTION 4 — iptables Firewall
# ============================================================================== #
header "STEP 4 · iptables Firewall"

# 4.1 Stop/disable firewalld, install iptables-services
info "Switching from firewalld to iptables-services …"
systemctl stop firewalld  2>/dev/null || true
systemctl disable firewalld 2>/dev/null || true
dnf install -y iptables-services &>/dev/null
systemctl enable iptables
success "iptables-services installed."

# 4.2 Apply rules
info "Applying iptables rules …"
IPT="iptables"

# Flush
${IPT} -F
${IPT} -X
${IPT} -t nat -F
${IPT} -t nat -X

# Default policies
${IPT} -P INPUT   DROP
${IPT} -P FORWARD DROP
${IPT} -P OUTPUT  ACCEPT

# Loopback
${IPT} -A INPUT -i lo -j ACCEPT

# Established / related
${IPT} -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

# ── OpenSSH ──
${IPT} -A INPUT -p tcp --dport "${SSH_PORT}" -m conntrack --ctstate NEW \
       -j LOG --log-prefix "< SSH TRAFFIC > " --log-level 4
${IPT} -A INPUT -p tcp --dport "${SSH_PORT}" -m conntrack --ctstate NEW -j ACCEPT

# ── Cowrie Honeypot ──
${IPT} -A INPUT -p tcp --dport "${COWRIE_PORT}" -m conntrack --ctstate NEW \
       -j LOG --log-prefix "<< HONEYPOT TRAFFIC >> " --log-level 4
${IPT} -A INPUT -p tcp --dport "${COWRIE_PORT}" -m conntrack --ctstate NEW -j ACCEPT

# ── Block & log everything else ──
${IPT} -A INPUT -j LOG --log-prefix "<<< BLOCKED TRAFFIC >>> " --log-level 4
${IPT} -A INPUT -j DROP

# 4.3 Persist
iptables-save > /etc/sysconfig/iptables
systemctl restart iptables
success "iptables rules active and persisted."

echo ""
info "Verify with:  iptables -L -v -n --line-numbers"
info "Log tail:     tail -f /var/log/messages | grep -E 'SSH TRAFFIC|HONEYPOT|BLOCKED'"

# ============================================================================== #
#  SECTION 5 — Snort IDS
# ============================================================================== #
header "STEP 5 · Snort 3 IDS"

# 5.1 Enable CRB repo and install build dependencies
info "Enabling CodeReady Builder repo …"
subscription-manager repos \
    --enable codeready-builder-for-rhel-10-x86_64-rpms 2>/dev/null || \
    dnf config-manager --set-enabled crb 2>/dev/null || \
    warn "Could not enable CRB repo automatically — you may need to do this manually."

info "Installing Snort build dependencies …"
dnf install -y cmake gcc gcc-c++ flex bison libpcap-devel pcre-devel \
               libdnet-devel hwloc-devel luajit-devel openssl-devel \
               zlib-devel libtirpc-devel libmnl-devel libunwind-devel \
               wget tar &>/dev/null
success "Build dependencies installed."

# 5.2 Build and install libdaq
LIBDAQ_VER="3.0.14"
SNORT_VER="3.3.7.0"

if ! ldconfig -p | grep -q libdaq; then
    info "Building libdaq ${LIBDAQ_VER} …"
    cd /tmp
    wget -q "https://github.com/snort3/libdaq/releases/download/v${LIBDAQ_VER}/libdaq-${LIBDAQ_VER}.tar.gz"
    tar -xzf "libdaq-${LIBDAQ_VER}.tar.gz"
    cd "libdaq-${LIBDAQ_VER}"
    ./configure --quiet && make -j"$(nproc)" && make install
    ldconfig
    success "libdaq installed."
else
    info "libdaq already present — skipping."
fi

# 5.3 Build and install Snort 3
if ! command -v snort &>/dev/null; then
    info "Building Snort ${SNORT_VER} (this may take several minutes) …"
    cd /tmp
    wget -q "https://github.com/snort3/snort3/releases/download/${SNORT_VER}/snort3-${SNORT_VER}.tar.gz"
    tar -xzf "snort3-${SNORT_VER}.tar.gz"
    cd "snort3-${SNORT_VER}"
    ./configure_cmake.sh --prefix=/usr/local --enable-tcmalloc --quiet
    cd build
    make -j"$(nproc)"
    make install
    success "Snort ${SNORT_VER} installed."
else
    info "Snort already installed — skipping build."
    snort --version 2>&1 | head -3
fi

# 5.4 Directory layout
info "Creating Snort directory layout …"
mkdir -p /usr/local/etc/snort/rules
mkdir -p /var/log/snort
chown -R root:root /usr/local/etc/snort /var/log/snort
success "Snort directories ready."

# 5.5 Write snort.lua
info "Writing snort.lua …"
cat > /usr/local/etc/snort/snort.lua <<LUA_EOF
-- ============================================================ --
-- snort.lua — Main Snort 3 Configuration
-- Generated by rhel10_security_setup.sh — $(date)
-- ============================================================ --

-- Network variables
HOME_NET = 'any'
EXTERNAL_NET = '!\$HOME_NET'

-- IPS engine (alert mode, load local rules)
ips =
{
    enable_builtin_rules = true,
    include = '/usr/local/etc/snort/rules/local.rules',
    mode = 'alert',
}

-- Fast alert output → /var/log/snort/alert_fast.txt
alert_fast =
{
    file   = true,
    packet = false,
    limit  = 100,   -- MB
}
LUA_EOF
success "snort.lua written."

# 5.6 Write local.rules (substituting the SSH port variable)
info "Writing Snort local.rules …"
cat > /usr/local/etc/snort/rules/local.rules <<RULES_EOF
# ============================================================== #
# Snort Local Rules
# Generated by rhel10_security_setup.sh — $(date)
# SSH port: ${SSH_PORT}
# ============================================================== #

# ────────────────────────────────────────────────────────────── #
# 1. ICMP Traffic (Diagnostic / Ping)
# ────────────────────────────────────────────────────────────── #
alert icmp any any -> \$HOME_NET any (msg:"ICMP Ping Detected"; itype:8; sid:1000001; rev:1;)
alert icmp any any -> \$HOME_NET any (msg:"ICMP Echo Reply Detected"; itype:0; sid:1000002; rev:1;)

# ────────────────────────────────────────────────────────────── #
# 2. TCP Traffic (Web, SSH, Email)
# ────────────────────────────────────────────────────────────── #
alert tcp any any -> \$HOME_NET 80    (msg:"TCP HTTP Traffic Detected";  flags:S; sid:1000010; rev:1;)
alert tcp any any -> \$HOME_NET 443   (msg:"TCP HTTPS Traffic Detected"; flags:S; sid:1000011; rev:1;)
alert tcp any any -> \$HOME_NET ${SSH_PORT} (msg:"TCP SSH Traffic Detected";  flags:S; sid:1000012; rev:1;)
alert tcp any any -> \$HOME_NET 25    (msg:"TCP SMTP Traffic Detected";  flags:S; sid:1000013; rev:1;)
alert tcp any any -> \$HOME_NET 143   (msg:"TCP IMAP Traffic Detected";  flags:S; sid:1000014; rev:1;)
alert tcp any any -> \$HOME_NET 110   (msg:"TCP POP3 Traffic Detected";  flags:S; sid:1000015; rev:1;)

# ────────────────────────────────────────────────────────────── #
# 3. UDP Traffic (DNS, NTP)
# ────────────────────────────────────────────────────────────── #
alert udp any any -> \$HOME_NET 53  (msg:"UDP DNS Query Detected"; sid:1000020; rev:1;)
alert udp any any -> \$HOME_NET 123 (msg:"UDP NTP Traffic Detected"; sid:1000021; rev:1;)

# ────────────────────────────────────────────────────────────── #
# 4. Web Attacks — SQL Injection
# ────────────────────────────────────────────────────────────── #
alert tcp any any -> \$HOME_NET [80,443,8080] (msg:"SQL Injection - UNION SELECT"; flow:to_server,established; content:"UNION"; nocase; content:"SELECT"; nocase; distance:0; sid:1000030; rev:1;)
alert tcp any any -> \$HOME_NET [80,443,8080] (msg:"SQL Injection - OR 1=1"; flow:to_server,established; content:"OR"; nocase; content:"1=1"; nocase; sid:1000031; rev:1;)
alert tcp any any -> \$HOME_NET [80,443,8080] (msg:"SQL Injection - DROP TABLE"; flow:to_server,established; content:"DROP"; nocase; content:"TABLE"; nocase; sid:1000032; rev:1;)
alert tcp any any -> \$HOME_NET [80,443,8080] (msg:"SQL Injection - Quote Probe"; flow:to_server,established; content:"'"; content:"--"; sid:1000033; rev:1;)

# ────────────────────────────────────────────────────────────── #
# 5. Inbound Reconnaissance — Nmap Scans
# ────────────────────────────────────────────────────────────── #
alert tcp any any -> \$HOME_NET any (msg:"Recon - Nmap FIN Scan";  flags:F,!APRSUC; threshold:type threshold, track by_src, count 5, seconds 2; sid:1000040; rev:1;)
alert tcp any any -> \$HOME_NET any (msg:"Recon - TCP NULL Scan";  flags:0;         threshold:type threshold, track by_src, count 5, seconds 2; sid:1000041; rev:1;)
alert tcp any any -> \$HOME_NET any (msg:"Recon - Nmap XMAS Scan"; flags:FPU;       threshold:type threshold, track by_src, count 5, seconds 2; sid:1000042; rev:1;)

# ────────────────────────────────────────────────────────────── #
# 6. C2 / Reverse Shells — Netcat
# ────────────────────────────────────────────────────────────── #
alert tcp any any -> \$HOME_NET any (msg:"C2 - Netcat bash -i reverse shell"; content:"bash"; nocase; content:"-i"; content:">&"; within:20; sid:1000050; rev:1;)
alert tcp any any -> \$HOME_NET any (msg:"C2 - Netcat /bin/sh payload";       content:"/bin/sh"; nocase; sid:1000051; rev:1;)
alert tcp any any -> \$HOME_NET any (msg:"C2 - Netcat nc -e shell";           content:"nc"; content:"-e"; within:5; sid:1000052; rev:1;)

# ────────────────────────────────────────────────────────────── #
# 7. DoS — ICMP Flood / Ping of Death
# ────────────────────────────────────────────────────────────── #
alert icmp any any -> \$HOME_NET any (msg:"DoS - ICMP Flood Attack";             itype:8; threshold:type both, track by_src, count 100, seconds 1; sid:1000060; rev:1;)
alert icmp any any -> \$HOME_NET any (msg:"DoS - Ping of Death (oversized ICMP)"; itype:8; dsize:>10000; sid:1000061; rev:1;)
RULES_EOF
success "local.rules written (${SSH_PORT} used for SSH rule)."

# 5.7 Validate rules syntax
info "Validating Snort configuration …"
if snort -c /usr/local/etc/snort/snort.lua -T &>/dev/null; then
    success "Snort configuration validated successfully."
else
    warn "Snort validation reported warnings — check manually:"
    snort -c /usr/local/etc/snort/snort.lua -T 2>&1 | tail -20
fi

# 5.8 systemd service for Snort
info "Creating systemd service for Snort …"
cat > /etc/systemd/system/snort.service <<SVC_EOF
[Unit]
Description=Snort 3 IDS
After=network.target

[Service]
Type=simple
ExecStart=/usr/local/bin/snort \\
    -c /usr/local/etc/snort/snort.lua \\
    -i ${NET_IFACE} \\
    -l /var/log/snort \\
    --daq-dir /usr/local/lib/daq \\
    -D
Restart=on-failure
RestartSec=5s

[Install]
WantedBy=multi-user.target
SVC_EOF

systemctl daemon-reload
systemctl enable snort
systemctl start snort || warn "Snort failed to start — check: journalctl -u snort"
success "Snort service enabled and started on interface ${NET_IFACE}."

# ============================================================================== #
#  FINAL SUMMARY
# ============================================================================== #
header "Setup Complete — Summary"

echo ""
echo -e "${BOLD}Employee:${RESET}      ${Employee_ID} / ${Employee_NAME}"
echo ""
echo -e "${BOLD}Services:${RESET}"
printf "  %-28s %s\n" "OpenSSH (hardened + MFA)"  "TCP port ${SSH_PORT}"
printf "  %-28s %s\n" "Cowrie Honeypot"            "TCP port ${COWRIE_PORT}"
printf "  %-28s %s\n" "Snort IDS"                  "passive on ${NET_IFACE}"
echo ""
echo -e "${BOLD}Service status:${RESET}"
for svc in sshd cowrie snort; do
    STATUS=$(systemctl is-active "$svc" 2>/dev/null || echo "unknown")
    if [[ "$STATUS" == "active" ]]; then
        echo -e "  ${GREEN}●${RESET} $svc — ${GREEN}${STATUS}${RESET}"
    else
        echo -e "  ${RED}●${RESET} $svc — ${RED}${STATUS}${RESET}"
    fi
done
echo ""
echo -e "${BOLD}Log locations:${RESET}"
printf "  %-30s %s\n" "SSH authentication"    "/var/log/secure"
printf "  %-30s %s\n" "iptables (kernel)"     "/var/log/messages"
printf "  %-30s %s\n" "Cowrie honeypot"       "/opt/cowrie/var/log/cowrie/cowrie.log"
printf "  %-30s %s\n" "Snort alerts"          "/var/log/snort/alert_fast.txt"
echo ""
echo -e "${BOLD}Firewall log prefixes:${RESET}"
echo "  < SSH TRAFFIC >        → SSH connections on port ${SSH_PORT}"
echo "  << HONEYPOT TRAFFIC >> → Cowrie connections on port ${COWRIE_PORT}"
echo "  <<< BLOCKED TRAFFIC >> → Everything else (dropped)"
echo ""
echo -e "${YELLOW}${BOLD}NEXT STEPS (manual — cannot be automated):${RESET}"
echo ""
echo "  1. On your CLIENT machine, generate and copy your SSH key:"
echo "       ssh-keygen -t ed25519 -f ~/.ssh/id_ed25519_rhel10"
echo "       ssh-copy-id -i ~/.ssh/id_ed25519_rhel10.pub -p ${SSH_PORT} <user>@<server_ip>"
echo ""
echo "  2. Enrol TOTP (run as each SSH user on the SERVER):"
echo "       google-authenticator"
echo "     Scan the QR code with Google Authenticator or Authy."
echo ""
echo "  3. Test your login BEFORE closing your current session:"
echo "       ssh -i ~/.ssh/id_ed25519_rhel10 -p ${SSH_PORT} <user>@<server_ip>"
echo ""
echo -e "${GREEN}${BOLD}All done!${RESET}"
